const TestimonialApi = [
  {
    id: 1,
    image: "https://d2j6dbq0eux0bg.cloudfront.net/startersite/images/47524064/1619973902160.jpg",
    design: "DOCTOR",
    name: "Dr. Mona Kakar",
    offcer: "Le Visage, Mumbai",
    post: "Doctor",
    date: "Le Visage Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Dr. Mona Kakar highly recommends Pyrax Dental Mart as a reliable and convenient platform for dental professionals to compare and purchase dental supplies. The user-friendly interface and comprehensive catalog make it easy to find the right products for specific needs.",
  },
  {
    id: 2,
    image: "https://d2j6dbq0eux0bg.cloudfront.net/startersite/images/47524064/1619974426400.jpg",
    design: "DOCTOR",
    name: "Dr. Mayank Vallabh",
    offcer: "Vallabh's Dental Studio, Haridwar",
    post: "DENTAL",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "Dr. Mayank Vallabh strongly endorses Pyrax Dental Mart as an exceptional dental products comparator website. As a dental professional, I have found their platform to be incredibly efficient and trustworthy for comparing and purchasing dental supplies. The extensive catalog, user-friendly interface, and reliable product information make it a go-to resource for dental professionals seeking high-quality dental products.",
  },
  {
    id: 3,
    image: "https://d2j6dbq0eux0bg.cloudfront.net/startersite/images/47524064/1619974551738.jpg",
    design: "DOCTOR",
    name: "Dr. Abdallah Nassar, Jerusalem",
    offcer: "DOCTOR",
    post: "DENTAL",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "Dr. Abdallah Nassar from Jerusalem highly recommends Pyrax Dental Mart as an outstanding dental products comparator website. As a dental professional, I have found their platform to be invaluable in sourcing and comparing dental supplies. The website's intuitive interface, comprehensive product range, and reliable customer reviews make it an essential tool for dental practitioners in making informed purchasing decisions.",
  },
  {
    id: 4,
    image: "./image/slide4.png",
    design: "Bound - Trolola",
    name: "Jone Duone Joe",
    offcer: "Operating Officer",
    post: "Web App Development",
    date: "Upwork - Mar 4, 2016 - Aug 30, 2021",
    desc: "Important fact to nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 5,
    image: "./image/slide5.png",
    design: "Glassfisom",
    name: "Nevine Dhawan",
    offcer: "CEO Of Officer",
    post: "Android App Design",
    date: "Fiver - Mar 4, 2015 - Aug 30, 2021",
    desc: "No more question for design. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris	.",
  },
]

export default TestimonialApi
